# https://docs.gitlab.com/omnibus/docker/
# https://stackoverflow.com/questions/45329240/cannot-make-request-to-gitlab-running-in-the-official-docker-container

# https://docs.gitlab.com/runner/install/docker.html
# one-liner:
# docker run -d --name gitlab-runner --restart always -v /data/docker/var/docker/volumes/gitlab-runner/config:/etc/gitlab-runner -v /var/run/docker.sock:/var/run/docker.sock gitlab/gitlab-runner:latest
# 
# register before using:
# docker run --rm -t -i -v /data/docker/var/docker/volumes/gitlab-runner/config:/etc/gitlab-runner gitlab/gitlab-runner:latest register

version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 64M

  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wow_secure_pass
    volumes:
      - /data/docker/var/docker/volumes/nextcloud/var/lib/mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 9090:80

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=wow_secure_pass
      - MYSQL_DATABASE=nextcloud
    ports:
      - 8080:80 # port 80 points to port 80 in the image
    volumes:
      - /data/docker/var/docker/volumes/nextcloud/var/www/html:/var/www/html

  gitea:
    image: gitea/gitea
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - '3000:3000'
      - '222:22'
    volumes:
      - /data/docker/var/docker/volumes/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - /data/docker/var/docker/volumes/jellyfin/config:/config
      - /data/docker/var/docker/volumes/jellyfin/cache:/cache
      - /media:/media:ro

networks:
  default:
    external:
      name: dockercloud

