# amalgamation of all docker-compose files in subdirs
# details and comments in each app's compose file

version: '2'

volumes:
  mariadb:
  nextcloud:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

services:
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=wow_secure_pass
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 9000:80
    links:
      - mariadb

  nextcloud:
    image: nextcloud
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=wow_secure_pass
      - NEXTCLOUD_TRUSTED_DOMAINS="desktopcookies.local 192.168.1.100 192.168.1.* 192.168.2.*"
    ports:
      - 8000:80
    volumes:
      - nextcloud:/var/www/html
    links:
      - mariadb

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      - "GITLAB_OMNIBUS_CONFIG=external_url 'http://192.168.1.100:8001'"
    ports:
      - 8001:8001
      - 2222:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
