version: '3'

services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        hostname: watchtower
        restart: always
        environment:
            - WATCHTOWER_POLL_INTERVAL=3600 # update every hour to prevent hitting docker hub's limit
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        hostname: nignx
        networks:
            dockercloud:
        restart: always
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - "80:80"
            - "443:443"
            - "8022:8022" # gitea ssh
        volumes:
            - /home/ubuntu/volumes/nginx:/etc/nginx/conf.d
            - /home/ubuntu/volumes/letsencrypt:/etc/letsencrypt
            - /home/ubuntu/volumes/certbot:/var/www/certbot
    certbot:
        image: certbot/certbot
        container_name: certbot
        hostname: certbot
        restart: always
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /home/ubuntu/volumes/letsencrypt:/etc/letsencrypt
            - /home/ubuntu/volumes/certbot:/var/www/certbot
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        hostname: gitea
        networks:
            dockercloud:
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: unless-stopped
        volumes:
            - /home/ubuntu/volumes/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    thelounge:
        image: thelounge/thelounge:latest
        container_name: thelounge
        hostname: thelounge
        networks:
            dockercloud:
        restart: unless-stopped
        volumes:
            - /home/ubuntu/volumes/thelounge:/var/opt/thelounge
    express_server:
        build: express_server
        container_name: express_server
        hostname: express_server
        networks:
            dockercloud:
        restart: always
        ports:
            - "8080:8080"

networks:
    dockercloud:
