version: '3'

services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        hostname: watchtower
        restart: always
        environment:
            - WATCHTOWER_POLL_INTERVAL=3600 # update every hour to prevent hitting docker hub's limit
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        hostname: nignx
        restart: always
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /data/srv/var/docker/volumes/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
            - /data/srv/var/docker/volumes/certbot/etc/letsencrypt:/etc/letsencrypt
            - /data/srv/var/docker/volumes/certbot/var/www/certbot:/var/www/certbot
    certbot:
        image: certbot/certbot
        container_name: certbot
        hostname: certbot
        restart: always
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /data/srv/var/docker/volumes/certbot/etc/letsencrypt:/etc/letsencrypt
            - /data/srv/var/docker/volumes/certbot/var/www/certbot:/var/www/certbot
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        hostname: gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: unless-stopped
        volumes:
            - /data/srv/var/docker/volumes/gitea/data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8022:22"
    thelounge:
        image: thelounge/thelounge:latest
        container_name: thelounge
        hostname: thelounge
        restart: unless-stopped
        volumes:
            - /data/srv/var/docker/volumes/thelounge/var/opt/thelounge:/var/opt/thelounge
    element:
        image: vectorim/element-web
        container_name: element-web
        hostname: element
        restart: unless-stopped
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        hostname: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=wow_secure_pass
        volumes:
            - /data/srv/var/docker/volumes/mariadb/var/lib/mysql:/var/lib/mysql
    nextcloud:
        image: nextcloud:production
        container_name: nextcloud
        hostname: nextcloud
        restart: unless-stopped
        environment:
            - MYSQL_HOST=mariadb
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=wow_secure_pass
        volumes:
            - /data/srv/var/docker/volumes/nextcloud/var/www/html:/var/www/html
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        restart: unless-stopped
        environment:
            - PMA_HOST=mariadb
    express_server:
        build: express_server
        container_name: express_server
        hostname: express_server
        restart: always
        ports:
            - "8080:8080"

networks:
    default:
        external:
            name: dockercloud
